import "./globals.css";
import { Outfit } from "next/font/google";
import Proivder from "./proivder";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "next-themes";
export const metadata = {
  title: "sailornotes",
  icons: {
    icon: "/metalogo.png", // Path to your logo in the public folder
  },
  description: "Generated by create next app",
};
const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={outfit.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Proivder>{children}</Proivder>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
