import "./globals.css";
import { Outfit } from "next/font/google";
import Proivder from "./proivder";
import { ClerkProvider } from "@clerk/nextjs";
export const metadata = {
  title: "sailornotes",
  icons: {
    icon: "/metalogo.png", // Path to your logo in the public folder
  },
  description: "Generated by create next app",
};
const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <Proivder>{children}</Proivder>
        </body>
      </html>
    </ClerkProvider>
  );
}
