import React from 'react'
import Sidebar from './_components/Sidebar'
import Header from './_components/Header'
import { Toaster } from 'sonner'
export const metadata = {
  title: "dashboard | sailornotes",
  icons: {
    icon: "/metalogo.png", // Path to your logo in the public folder
  },
  description: "Generated by create next app",
};
const DashboardLayout = ({children}) => {
  return (
    <div>
      <div  className='shadow-lg h-screen fixed md:w-70'>
        <Sidebar/>
      </div>
      <div className='md:ml-74'>
        <Header></Header>
        <div className='p-12'>
        {children}
        <Toaster/>
        </div>
        </div>
      
      </div>
  )
}

export default DashboardLayout
